### ISSUE TITLE
unable to Download Plugins ... your Nginx Server is only giving back a 503 Status Code on any attempt to download plugins

### ISSUE THREAD

**Issue by markus-meisterernst** [jenkins-infra/plugin-site#466]
Hi, 

just wanted to let you know that the plugin download section is currently unavailable.

504 Gateway Time-out
nginx/1.19.1

Hope I can reach you this way.

Cheers,

Markus

e.g. 
https://updates.jenkins.io/download/plugins/matrix-project/1.18/matrix-project.hpi
https://get.jenkins.io/plugins/junit/1.29/junit.hpi
...
```
2020-11-12 21:52:55.728+0000 [id=89]	SEVERE	h.model.UpdateCenter$DownloadJob#run: Failed to install junit
java.io.IOException: Server returned HTTP response code: 503 for URL: https://get.jenkins.io/plugins/junit/1.29/junit.hpi
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3051)
	at java.net.URLConnection.getHeaderFieldLong(URLConnection.java:629)
	at java.net.URLConnection.getContentLengthLong(URLConnection.java:501)
	at java.net.URLConnection.getContentLength(URLConnection.java:485)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentLength(HttpsURLConnectionImpl.java:407)
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1161)
Caused: java.io.IOException: Server returned HTTP response code: 503 for URL: https://get.jenkins.io/plugins/junit/1.29/junit.hpi
	at sun.reflect.GeneratedConstructorAccessor44.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1944)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1939)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1938)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1508)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1177)
Caused: java.io.IOException: Failed to load https://updates.jenkins.io/download/plugins/junit/1.29/junit.hpi to /data/plugins/junit.jpi.tmp
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1184)
Caused: java.io.IOException: Failed to download from https://updates.jenkins.io/download/plugins/junit/1.29/junit.hpi (redirected to: https://get.jenkins.io/plugins/junit/1.29/junit.hpi)
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1218)
	at hudson.model.UpdateCenter$DownloadJob._run(UpdateCenter.java:1766)
	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:2037)
	at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1740)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:112)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by timja** [comment]
follow twitter for updates please https://twitter.com/jenkinsci/status/1326994705230393344

**Comment by davidcsi** [comment]
Hello, I know you're still down. I was wondering if there's an alternative to installing the initial pluins? I'm just started a docker with jenkins but i'm stuck...

Thanks

**Comment by timja** [comment]
It’s back up now

**Comment by davidcsi** [comment]
@timja Thanks! It's working now... I retried about an hour ago and it was still down.
Again thanks!
