### ISSUE TITLE
Extended Choice Parameter page - Nexus 3 add new attributes causing a mapping error

### ISSUE THREAD

**Issue by fyrnaga** [jenkins-infra/plugin-site#559]
Problem with the [Extended Choice Parameter](https://plugins.jenkins.io/extended-choice-parameter) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

We updated our nexus repository recently and now new attributes are returned for NPM repository in the asset information. It seems to break the selection list.

## Screenshots 

**Nexus API**
```
....
, {
    "id" : "....",
    "repository" : "npm-public",
    "format" : "npm",
    "group" : "cloudops",
    "name" : "cloudmc-ui",
    "version" : "21.1.0-SNAPSHOT",
    "assets" : [ {
      "downloadUrl" : "https://repository/npm-public/@cloudops/cloudmc-ui/-/cloudmc-ui-21.1.0-SNAPSHOT.tgz",
      "path" : "@cloudops/cloudmc-ui/-/cloudmc-ui-21.1.0-SNAPSHOT.tgz",
      "id" : "....",
      "repository" : "npm-public",
      "format" : "npm",
      "checksum" : {
        "sha1" : "...."
      },
      "contentType" : "application/x-tgz",
      "lastModified" : "2020-06-09T16:00:56.682+00:00",
      "npm" : {
        "name" : "@cloudops/cloudmc-ui",
        "version" : "21.1.0-SNAPSHOT"
      }
    } ]
```
**Logs**
```
2021-01-08 21:01:09.267+0000 [id=52087]	WARNING	o.j.p.m.n.Nexus3RestApiSearchService#callService: failed to map
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "npm" (class org.jenkinsci.plugins.maven_artifact_choicelistprovider.nexus3.Item), not marked as ignorable (9 known properties: "checksum", "path", "downloadUrl", "repository", "id", "lastModified", "contentType", "format", "maven2"])
 at [Source: (String)"{
  "items" : [ {
    "downloadUrl" : "https://..../repository/npm-internal/@cloudops/cloudmc-ui/-/cloudmc-ui-11.0.0.tgz",
    "path" : "@cloudops/cloudmc-ui/-/cloudmc-ui-11.0.0.tgz",
    "id" : "....",
    "repository" : "npm-internal",
    "format" : "npm",
    "checksum" : {
      "sha1" : "...."
    },
    "contentType" : "application/x-tgz",
    "lastModified" : "2018-10-18T20:18:39.900"[truncated 29334 chars]; line: 13, column: 14] (through reference chain: org.jenkinsci.plugins.maven_artifact_choicelistprovider.nexus3.Nexus3RestResponse["items"]->java.lang.Object[][0]->org.jenkinsci.plugins.maven_artifact_choicelistprovider.nexus3.Item["npm"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:823)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1153)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1589)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1567)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:195)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:21)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)
	at org.jenkinsci.plugins.maven_artifact_choicelistprovider.nexus3.Nexus3RestApiSearchService.callService(Nexus3RestApiSearchService.java:54)
	at org.jenkinsci.plugins.maven_artifact_choicelistprovider.AbstractRESTfulVersionReader.retrieveVersions(AbstractRESTfulVersionReader.java:70)
	at org.jenkinsci.plugins.maven_artifact_choicelistprovider.AbstractMavenArtifactChoiceListProvider.readURL(AbstractMavenArtifactChoiceListProvider.java:116)
	at org.jenkinsci.plugins.maven_artifact_choicelistprovider.nexus3.Nexus3ChoiceListProvider$Nexus3DescriptorImpl.wrapTestConnection(Nexus3ChoiceListProvider.java:98)
	at org.jenkinsci.plugins.maven_artifact_choicelistprovider.AbstractMavenArtifactDescriptorImpl.performTest(AbstractMavenArtifactDescriptorImpl.java:59)
	at org.jenkinsci.plugins.maven_artifact_choicelistprovider.nexus3.Nexus3ChoiceListProvider$Nexus3DescriptorImpl.doTest(Nexus3ChoiceListProvider.java:92)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)
```
## Possible Solution 

 

Adding the ignore parameters not recognized.

**Comment by timja** [comment]
Hi, 

Thank you very much for the report, but the issue tracker for the plugins.jenkins.io site is used to track issues with the plugin site itself. Your request seems to be a request for help, not a report of a functionality issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions or even create a bug on the [issues site](https://issues.jenkins-ci.org)
