### ISSUE TITLE
Facing GIT plugin issue while job execution

### ISSUE THREAD

**Issue by geetanjalikamble-jade** [jenkins-infra/plugin-site#829]
I have installed Jenkins on local host, where I have configure a job to execute my project. 
As I am fetching the the code from GIT HUB, I have installed GIT plugin as well.

But I facing issue while the job run. getting below log error-
**_Started by user ADMIN
Running as SYSTEM
Building in workspace C:\Windows\system32\config\systemprofile\AppData\Local\Jenkins\.jenkins\workspace\Project
The recommended git tool is: 
using credential 
Cloning the remote Git repository
Cloning repository https://github.com/jadeqa/repo.git
 > C:\Program Files\Git\cmd\git.exe init C:\Windows\system32\config\systemprofile\AppData\Local\Jenkins\.jenkins\workspace\Project # timeout=10
Fetching upstream changes from https://github.com/jadeqa/repo.git
 > C:\Program Files\Git\cmd\git.exe --version # timeout=10
 > git --version # 'git version 2.33.1.windows.1'
using GIT_ASKPASS to set credentials 
 > C:\Program Files\Git\cmd\git.exe fetch --tags --force --progress -- https://github.com/jadeqa/repo.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > C:\Program Files\Git\cmd\git.exe config remote.origin.url https://github.com/jadeqa/repo.git # timeout=10
 > C:\Program Files\Git\cmd\git.exe config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
Avoid second fetch
 > C:\Program Files\Git\cmd\git.exe rev-parse "refs/remotes/origin/dev^{commit}" # timeout=10
Checking out Revision 4726c510ef7be5d51335a4bf34bcc4a2ba640c81 (refs/remotes/origin/dev)
 > C:\Program Files\Git\cmd\git.exe config core.sparsecheckout # timeout=10
 > C:\Program Files\Git\cmd\git.exe checkout -f 4726c510ef7be5d51335a4bf34bcc4a2ba640c81 # timeout=10
ERROR: Unable to retrieve commit message
org.eclipse.jgit.errors.MissingObjectException: Missing unknown 4726c510ef7be5d51335a4bf34bcc4a2ba640c81
	at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:135)
	at org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:212)
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:1068)
	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:978)
	at hudson.plugins.git.util.RevCommitRepositoryCallback.invoke(RevCommitRepositoryCallback.java:25)
	at hudson.plugins.git.util.RevCommitRepositoryCallback.invoke(RevCommitRepositoryCallback.java:13)
	at org.jenkinsci.plugins.gitclient.AbstractGitAPIImpl.withRepository(AbstractGitAPIImpl.java:29)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.withRepository(CliGitAPIImpl.java:86)
	at hudson.plugins.git.GitSCM.printCommitMessageToLog(GitSCM.java:1394)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1360)
	at hudson.scm.SCM.checkout(SCM.java:505)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1213)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:637)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:85)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:509)
	at hudson.model.Run.execute(Run.java:1888)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
	at hudson.model.ResourceController.execute(ResourceController.java:99)
	at hudson.model.Executor.run(Executor.java:431)
 > C:\Program Files\Git\cmd\git.exe rev-list --no-walk 4726c510ef7be5d51335a4bf34bcc4a2ba640c81 # timeout=10
Parsing POMs
ERROR: No such file C:\Windows\system32\config\systemprofile\AppData\Local\Jenkins\.jenkins\workspace\Project\pom.xml
Perhaps you need to specify the correct POM file path in the project configuration?
Finished: FAILURE_**

There is no proper solution which I could find for this error. The version currently present on Jenkins is 4.9.0.

![image](https://user-images.githubusercontent.com/87296506/138094506-8d85fe7a-b35a-4b82-bafe-a0811df80ea8.png)

Is this a know bug by Jenkins, If yes could you please help us with the proper resolution over the same.
Contact details -
Priyanka Rathod - priyanka.rathod@jadeglobal.com
Mayur Dugad - mayur.dugad@jadeglobal.com

Thanks,
Priyanka Rathod.

**Comment by geetanjalikamble-jade** [comment]
updated

**Comment by timja** [comment]
Hi, 

Thank you very much for the report, but the issue tracker for the plugins.jenkins.io site is used to track issues with the plugin site itself. Your request seems to be a request for help, not a report of a functionality issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/), [community forum](https://community.jenkins.io) or the [chat channels](https://www.jenkins.io/chat/) for questions or even create a bug on the [issues site](https://issues.jenkins.io)
